# Generated by Django 3.1.1 on 2020-09-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow')], db_index=True, default='red', max_length=6),
            preserve_default=False,
        ),
    ]
