# Generated by Django 3.1.1 on 2020-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('yellow', 'Yellow')], db_index=True, max_length=6),
        ),
    ]
