# Generated by Django 3.1.1 on 2020-09-27 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200927_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='row',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
